# Generated by Django 5.2.12 on 2026-03-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firmwares', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('changes', models.JSONField(blank=True, default=list, help_text='Structured list of change objects {type, description}')),
                ('release_date', models.DateField(db_index=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Changelog Entry',
                'verbose_name_plural': 'Changelog Entries',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('feature', 'New Feature'), ('improvement', 'Improvement'), ('bug_fix', 'Bug Fix'), ('security', 'Security'), ('breaking', 'Breaking Change'), ('deprecated', 'Deprecation')], max_length=15)),
                ('description', models.TextField()),
                ('is_breaking', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_notes', to='changelog.changelogentry')),
            ],
            options={
                'verbose_name': 'Release Note',
                'verbose_name_plural': 'Release Notes',
            },
        ),
        migrations.CreateModel(
            name='FirmwareDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_html', models.TextField(blank=True, default='')),
                ('diff_text', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('new_firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_as_new', to='firmwares.officialfirmware')),
                ('old_firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_as_old', to='firmwares.officialfirmware')),
            ],
            options={
                'verbose_name': 'Firmware Diff',
                'verbose_name_plural': 'Firmware Diffs',
                'unique_together': {('old_firmware', 'new_firmware')},
            },
        ),
    ]
