# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(default='custom', max_length=50)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('base_params', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Keyword Provider',
                'verbose_name_plural': 'Keyword Providers',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Use concise, reusable names.', max_length=64, unique=True)),
                ('normalized_name', models.CharField(blank=True, max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Explain when to use this tag.')),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='Comma-separated alternatives users might search.')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('co_occurrence', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_suggested', models.BooleanField(default=False, help_text='True if suggested by AI and not yet curated.')),
                ('is_curated', models.BooleanField(default=False, help_text='True if reviewed/approved by staff.')),
                ('path_cache', models.CharField(blank=True, default='', help_text='Cached materialized path for fast tree queries.', max_length=255)),
                ('ai_score', models.FloatField(default=0.0, help_text='Confidence when AI suggested this tag.')),
                ('content_hash', models.CharField(blank=True, default='', help_text='Last content hash used for AI suggestions.', max_length=64)),
                ('last_suggested_at', models.DateTimeField(blank=True, null=True)),
                ('suggestions', models.JSONField(blank=True, default=list, help_text='Recent AI suggestions with scores/rationales.')),
                ('importance', models.IntegerField(default=0, help_text='Boost for curated/priority tags.')),
                ('synonyms_text', models.TextField(blank=True, default='', help_text='Editable comma-separated synonyms.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, help_text='The ID of the specific object being tagged')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tagged Item',
                'verbose_name_plural': 'Tagged Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_public_suggestions', models.BooleanField(default=True, help_text='Allow authenticated users to suggest new tags.')),
                ('enable_ai_suggestions', models.BooleanField(default=True, help_text='Enable AI-assisted tag suggestions where available.')),
                ('show_tag_usage', models.BooleanField(default=True, help_text='Expose tag usage counts in public views.')),
            ],
            options={
                'verbose_name': 'Tags Settings',
            },
        ),
        migrations.CreateModel(
            name='KeywordSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128)),
                ('normalized', models.CharField(db_index=True, max_length=128)),
                ('score', models.FloatField(default=0.0)),
                ('locale', models.CharField(blank=True, default='', max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='tags.keywordprovider')),
            ],
        ),
    ]
