# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='merge_into',
            field=models.ForeignKey(blank=True, help_text='Soft-merge: redirects this tag to another canonical tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent for hierarchical taxonomies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='content_type',
            field=models.ForeignKey(help_text='The model class being tagged', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who applied this tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(help_text='The tag being applied', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='tags.tag'),
        ),
        migrations.AddIndex(
            model_name='keywordsuggestion',
            index=models.Index(fields=['normalized'], name='tags_keywor_normali_79f9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordsuggestion',
            index=models.Index(fields=['locale', 'category'], name='tags_keywor_locale_c6b8ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keywordsuggestion',
            unique_together={('provider', 'normalized')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['normalized_name'], name='tag_normalized_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='tag_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active', 'importance', '-usage_count'], name='tag_active_importance_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['merge_into'], name='tag_merge_into_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['parent'], name='tag_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['path_cache'], name='tag_path_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('merge_into__isnull', True)), fields=('normalized_name',), name='tag_unique_normalized'),
        ),
        migrations.AddIndex(
            model_name='taggeditem',
            index=models.Index(fields=['content_type', 'object_id'], name='tags_tagged_content_eaa81e_idx'),
        ),
        migrations.AddIndex(
            model_name='taggeditem',
            index=models.Index(fields=['tag', 'content_type'], name='tags_tagged_tag_id_eb7179_idx'),
        ),
        migrations.AddIndex(
            model_name='taggeditem',
            index=models.Index(fields=['created_at'], name='tags_tagged_created_90a048_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
    ]
