# Generated by Django 5.2.12 on 2026-04-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
