# Generated by Django 5.2.12 on 2026-03-18 19:37

import apps.api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('rate_limit', models.PositiveIntegerField(default=100, help_text='Requests per minute')),
                ('is_deprecated', models.BooleanField(default=False)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Endpoint',
                'verbose_name_plural': 'API Endpoints',
                'ordering': ['path', 'method'],
                'unique_together': {('path', 'method')},
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(db_index=True, default=apps.api.models._gen_key_prefix, max_length=20, unique=True)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list, help_text="List of scope strings e.g. ['read:firmware', 'write:firmware']")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_code', models.PositiveSmallIntegerField()),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='api.apikey')),
            ],
            options={
                'verbose_name': 'API Usage Log',
                'verbose_name_plural': 'API Usage Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_key', 'timestamp'], name='apilog_key_ts_idx')],
            },
        ),
    ]
