# Generated by Django 5.2.12 on 2026-03-18 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uri', models.URLField(blank=True, default='', max_length=512)),
                ('blocked_uri', models.URLField(blank=True, default='', max_length=512)),
                ('violated_directive', models.CharField(blank=True, default='', max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CSP Violation Report',
                'verbose_name_plural': 'CSP Violation Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_pattern', models.CharField(max_length=255, unique=True)),
                ('limit', models.PositiveIntegerField(default=100, help_text='Requests per window')),
                ('window_seconds', models.PositiveIntegerField(default=60)),
                ('action', models.CharField(choices=[('throttle', 'Throttle'), ('block', 'Block'), ('log', 'Log Only')], default='throttle', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rate Limit Rule',
                'verbose_name_plural': 'Rate Limit Rules',
                'ordering': ['path_pattern'],
            },
        ),
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_enabled', models.BooleanField(default=True)),
                ('mfa_policy', models.CharField(choices=[('optional', 'Optional'), ('required', 'Required'), ('risk_based', 'Risk-Based')], default='optional', max_length=20)),
                ('security_tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('strict', 'Strict')], default='standard', max_length=16)),
                ('login_risk_enabled', models.BooleanField(default=True)),
                ('device_quota_enforcement', models.BooleanField(default=False)),
                ('default_device_limit', models.PositiveIntegerField(default=5)),
                ('default_device_window', models.CharField(choices=[('3m', '3 Months'), ('6m', '6 Months'), ('12m', '12 Months')], default='12m', max_length=4)),
                ('max_failed_logins', models.PositiveIntegerField(default=5)),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=15)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('crawler_guard_enabled', models.BooleanField(default=True)),
                ('csrf_trusted_origins', models.JSONField(blank=True, default=list)),
                ('allowed_upload_extensions', models.JSONField(blank=True, default=list, help_text="Allowlist of file extensions for firmware uploads e.g. ['.zip', '.img']")),
                ('max_upload_size_mb', models.PositiveIntegerField(default=500)),
            ],
            options={
                'verbose_name': 'Security Config',
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('blocked_until', models.DateTimeField(blank=True, help_text='Null = permanent block', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_fail', 'Login Failure'), ('login_success', 'Login Success'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('mfa_fail', 'MFA Failure'), ('rate_limited', 'Rate Limited'), ('ip_blocked', 'IP Blocked'), ('csrf_fail', 'CSRF Failure'), ('file_upload', 'File Upload'), ('admin_action', 'Admin Action'), ('suspicious', 'Suspicious Activity'), ('bot_detected', 'Bot Detected'), ('download_abuse', 'Download Abuse')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='sec_event_type_ts_idx'), models.Index(fields=['ip', 'created_at'], name='sec_event_ip_ts_idx')],
            },
        ),
    ]
