# Generated by Django 5.2.12 on 2026-03-18 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path_pattern', models.CharField(help_text='fnmatch-style pattern e.g. /api/*', max_length=255)),
                ('requests_per_minute', models.PositiveIntegerField(default=60)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('throttle', 'Throttle'), ('block', 'Block'), ('challenge', 'Challenge')], default='allow', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(default=0, help_text='Higher value wins. Evaluated descending.')),
                ('stop_processing', models.BooleanField(default=False, help_text='If matched and allowed, stop evaluating further rules.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crawler Rule',
                'verbose_name_plural': 'Crawler Rules',
                'db_table': 'crawler_guard_crawlerrule',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='crawler_default_action',
            field=models.CharField(choices=[('allow', 'Allow'), ('throttle', 'Throttle'), ('block', 'Block'), ('challenge', 'Challenge')], default='allow', max_length=16),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='device_quota_enforcement_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='devices_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='login_risk_policy',
            field=models.CharField(choices=[('log_only', 'Log Only'), ('mfa_if_high', 'Require MFA if High Risk'), ('block_if_critical', 'Block if Critical')], default='mfa_if_high', max_length=32),
        ),
        migrations.CreateModel(
            name='CrawlerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=45)),
                ('device_identifier', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('path', models.CharField(max_length=255)),
                ('action_taken', models.CharField(choices=[('allow', 'Allow'), ('throttle', 'Throttle'), ('block', 'Block'), ('challenge', 'Challenge')], default='allow', max_length=20)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('headers_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule_triggered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='security.crawlerrule')),
            ],
            options={
                'verbose_name': 'Crawler Event',
                'verbose_name_plural': 'Crawler Events',
                'db_table': 'crawler_guard_crawlerevent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip', 'created_at'], name='cg_ip_ts_idx'), models.Index(fields=['action_taken'], name='cg_action_idx')],
            },
        ),
    ]
