# Generated by Django 5.2.12 on 2026-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_crawlerrule_securityconfig_crawler_default_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerevent',
            name='device_identifier',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='crawlerevent',
            name='headers_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
