# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('basic_fingerprinting', models.BooleanField(default=True)),
                ('enhanced_fingerprinting', models.BooleanField(default=False)),
                ('device_locking_mode', models.CharField(choices=[('none', 'None'), ('soft', 'Soft'), ('strict', 'Strict')], default='none', max_length=20)),
                ('mfa_requirement', models.CharField(choices=[('none', 'None'), ('new_device', 'New Device'), ('always', 'Always')], default='none', max_length=20)),
                ('ai_risk_scoring', models.BooleanField(default=False)),
                ('service_level_rules', models.JSONField(blank=True, default=dict)),
                ('monthly_device_quota', models.PositiveIntegerField(blank=True, help_text='Maximum new devices per user per month for this app (None = use global).', null=True)),
                ('yearly_device_quota', models.PositiveIntegerField(blank=True, help_text='Maximum new devices per user per calendar year for this app (None = use global).', null=True)),
                ('ad_unlock_enabled', models.BooleanField(default=False, help_text='Allow ad-based unlocks for device quota in this app.')),
            ],
            options={
                'verbose_name': 'App Policy',
                'verbose_name_plural': 'App Policies',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('os_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('os_name', models.CharField(blank=True, default='', max_length=50)),
                ('os_version', models.CharField(blank=True, default='', max_length=50)),
                ('hardware_uuid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('device_key_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('key_algorithm', models.CharField(blank=True, choices=[('ES256', 'ES256'), ('Ed25519', 'Ed25519')], default='ES256', max_length=20)),
                ('public_key', models.TextField(blank=True, default='')),
                ('fingerprint_hash', models.CharField(blank=True, default='', max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('browser_family', models.CharField(blank=True, default='', max_length=50)),
                ('os_family', models.CharField(blank=True, default='', max_length=50)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_trusted', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('risk_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('max_privilege_level', models.CharField(choices=[('normal', 'Normal'), ('restricted', 'Restricted'), ('blocked', 'Blocked')], default='normal', max_length=20)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_fingerprinting_enabled', models.BooleanField(default=True)),
                ('enhanced_fingerprinting_enabled', models.BooleanField(default=False)),
                ('enterprise_device_management_enabled', models.BooleanField(default=False)),
                ('max_devices_default', models.PositiveIntegerField(default=5)),
                ('monthly_device_quota', models.PositiveIntegerField(blank=True, help_text='Maximum new devices per user per month (None = unlimited).', null=True)),
                ('yearly_device_quota', models.PositiveIntegerField(blank=True, help_text='Maximum new devices per user per calendar year (None = unlimited).', null=True)),
                ('ad_unlock_enabled', models.BooleanField(default=False, help_text='Allow users to unlock device quota by completing rewarded ads.')),
                ('strict_new_device_login', models.BooleanField(default=False)),
                ('require_mfa_on_new_device', models.BooleanField(default=False)),
                ('device_expiry_days', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_server_fallback', models.BooleanField(default=True)),
                ('ai_risk_scoring_enabled', models.BooleanField(default=False)),
                ('risk_mfa_threshold', models.PositiveIntegerField(default=75, help_text='If a device risk score meets/exceeds this value, require MFA to continue.')),
            ],
            options={
                'verbose_name': 'Device Config',
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('download_attempt', 'Download Attempt'), ('policy_violation', 'Policy Violation'), ('registration', 'Registration'), ('device_trusted', 'Device Trusted'), ('device_blocked', 'Device Blocked'), ('mfa_challenge', 'MFA Challenge'), ('mfa_failed', 'MFA Failed'), ('mfa_passed', 'MFA Passed'), ('service_access', 'Service Access')], max_length=50)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('geo_region', models.CharField(blank=True, default='', max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDeviceQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_devices', models.PositiveIntegerField(blank=True, help_text='Override max devices; null = default', null=True)),
                ('window', models.CharField(choices=[('3m', '3 Months'), ('6m', '6 Months'), ('12m', '12 Months')], default='6m', max_length=4)),
                ('last_reset_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'User Device Quota',
                'verbose_name_plural': 'User Device Quotas',
            },
        ),
    ]
