# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='devices.device'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdevicequota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_quotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'os_fingerprint'], name='device_user_osfp_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_blocked'], name='device_blocked_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen_at'], name='device_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['risk_score'], name='device_risk_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'os_fingerprint'), name='device_user_os_fingerprint_unique'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['user'], name='device_event_user_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device'], name='device_event_device_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['event_type'], name='device_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['created_at'], name='device_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['success'], name='device_event_success_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicequota',
            index=models.Index(fields=['user'], name='devices_use_user_id_a5e3ba_idx'),
        ),
    ]
