# Generated by Django 5.2.12 on 2026-03-18 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('min_trust_score', models.FloatField(default=0.0)),
                ('max_trust_score', models.FloatField(default=100.0)),
                ('daily_download_limit', models.PositiveIntegerField(default=5)),
                ('hourly_download_limit', models.PositiveIntegerField(default=2)),
                ('requires_ad', models.BooleanField(default=False)),
                ('can_bypass_captcha', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quota Tier',
                'verbose_name_plural': 'Quota Tiers',
                'db_table': 'device_registry_quotatier',
                'ordering': ['min_trust_score'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=3)),
                ('trust_level', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('trusted', 'Trusted')], default='unknown', max_length=12)),
                ('is_bot', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Fingerprint',
                'verbose_name_plural': 'Device Fingerprints',
                'db_table': 'device_registry_devicefingerprint',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_insights', to=settings.AUTH_USER_MODEL)),
                ('fingerprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_insights', to='devices.devicefingerprint')),
            ],
            options={
                'verbose_name': 'Behavior Insight',
                'verbose_name_plural': 'Behavior Insights',
                'db_table': 'device_registry_behaviorinsight',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('visit', 'Visit'), ('dl_start', 'Download Start'), ('dl_complete', 'Download Complete'), ('ad_view', 'Ad View'), ('login', 'Login'), ('signup', 'Signup'), ('fp_change', 'Fingerprint Change')], max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_events', to='devices.devicefingerprint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registry Event',
                'verbose_name_plural': 'Registry Events',
                'db_table': 'device_registry_deviceevent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('signals_passed', models.PositiveIntegerField(default=0)),
                ('signals_failed', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('fingerprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to='devices.devicefingerprint')),
            ],
            options={
                'verbose_name': 'Trust Score',
                'db_table': 'device_registry_trustscore',
            },
        ),
    ]
