# Generated by Django 5.2.12 on 2026-03-18 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pattern', models.TextField(help_text='Regex pattern or keyword list (one per line)')),
                ('match_mode', models.CharField(choices=[('regex', 'Regex'), ('keywords', 'Keywords'), ('ml', 'ML Model')], default='keywords', max_length=10)),
                ('action', models.CharField(choices=[('flag', 'Flag for Review'), ('remove', 'Auto-Remove'), ('ban', 'Ban User'), ('shadow', 'Shadow Ban')], default='flag', max_length=10)),
                ('severity', models.SmallIntegerField(default=1, help_text='1=low … 5=critical')),
                ('applies_to', models.CharField(default='comment', help_text='content type label the rule applies to', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moderation Rule',
                'verbose_name_plural': 'Moderation Rules',
                'ordering': ['-severity'],
            },
        ),
        migrations.CreateModel(
            name='ModerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField(db_index=True)),
                ('report_reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('appealed', 'Under Appeal'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=12)),
                ('auto_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
                ('rule_triggered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.moderationrule')),
            ],
            options={
                'verbose_name': 'Moderation Item',
                'verbose_name_plural': 'Moderation Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('appealed', 'Under Appeal'), ('escalated', 'Escalated')], max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderation.moderationitem')),
            ],
            options={
                'verbose_name': 'Moderation Action',
                'verbose_name_plural': 'Moderation Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_appeals', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='moderation.moderationitem')),
            ],
            options={
                'verbose_name': 'Appeal',
                'verbose_name_plural': 'Appeals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='moderationitem',
            index=models.Index(fields=['status', 'content_type'], name='mod_item_status_ct_idx'),
        ),
    ]
