# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('ai_run_id', models.CharField(blank=True, default='', max_length=100)),
                ('last_error', models.TextField(blank=True, default='')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_blog', models.BooleanField(default=True)),
                ('enable_blog_comments', models.BooleanField(default=True)),
                ('allow_user_blog_posts', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Blog Settings',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Category Translation',
                'verbose_name_plural': 'Category Translations',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='3-200 characters.', max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)])),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('summary', models.TextField(blank=True, default='', help_text='Short abstract shown in lists; capped to ~1000 characters.', validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('seo_title', models.CharField(blank=True, default='', max_length=240)),
                ('seo_description', models.CharField(blank=True, default='', max_length=320)),
                ('canonical_url', models.URLField(blank=True, default='')),
                ('hero_image', models.URLField(blank=True, default='')),
                ('body', models.TextField(help_text='HTML produced by the WYSIWYG editor; validated and sanitized upstream.', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(50000)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Minutes')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_run_id', models.CharField(blank=True, default='', max_length=100)),
                ('ai_error', models.TextField(blank=True, default='')),
                ('allow_comments', models.BooleanField(default=True)),
                ('noindex', models.BooleanField(default=False, help_text='If true, exclude from indexing until manually cleared.')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Total views')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Total likes')),
                ('comments_count', models.PositiveIntegerField(default=0, help_text='Total comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('body', models.TextField(blank=True, default='')),
                ('seo_title', models.CharField(blank=True, default='', max_length=240)),
                ('seo_description', models.CharField(blank=True, default='', max_length=320)),
            ],
            options={
                'verbose_name': 'Post Translation',
                'verbose_name_plural': 'Post Translations',
            },
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Tag Translation',
                'verbose_name_plural': 'Tag Translations',
            },
        ),
    ]
