# Generated by Django 5.2.12 on 2026-03-22 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        ('firmwares', '0011_brand_description_brand_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='firmware_brand',
            field=models.ForeignKey(blank=True, help_text='Auto-linked brand for firmware-related blog posts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='firmwares.brand'),
        ),
        migrations.AddField(
            model_name='post',
            name='firmware_model',
            field=models.ForeignKey(blank=True, help_text='Auto-linked model for firmware-related blog posts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='firmwares.model'),
        ),
    ]
