# Generated by Django 5.2.12 on 2026-03-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_adevent_campaign_alter_adevent_creative_and_more'),
        ('blog', '0003_post_firmware_brand_post_firmware_model'),
        ('forum', '0003_forumattachment_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ad_gate_config',
            field=models.ForeignKey(blank=True, help_text="Rewarded ad configuration for this post's gate.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_posts', to='ads.rewardedadconfig'),
        ),
        migrations.AddField(
            model_name='post',
            name='ad_gate_enabled',
            field=models.BooleanField(default=False, help_text='Manual toggle: require ad view before reading full article.'),
        ),
        migrations.AddField(
            model_name='post',
            name='ad_gate_min_views',
            field=models.PositiveIntegerField(default=0, help_text='Auto-enable ad gate when views_count >= this value. 0 = disabled.'),
        ),
        migrations.AddField(
            model_name='post',
            name='forum_topic',
            field=models.ForeignKey(blank=True, help_text='Auto-linked forum discussion topic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='forum.forumtopic'),
        ),
    ]
