# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.CharField(blank=True, default='', max_length=320)),
                ('focus_keywords', models.JSONField(blank=True, default=list)),
                ('canonical_url', models.URLField(blank=True, default='')),
                ('robots_directives', models.CharField(blank=True, default='', max_length=255)),
                ('social_title', models.CharField(blank=True, default='', max_length=255)),
                ('social_description', models.CharField(blank=True, default='', max_length=320)),
                ('social_image', models.URLField(blank=True, default='')),
                ('noindex', models.BooleanField(default=False)),
                ('nofollow', models.BooleanField(default=False)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('ai_score', models.FloatField(default=0.0)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=255, unique=True)),
                ('target', models.CharField(max_length=255)),
                ('is_permanent', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['source'],
            },
        ),
        migrations.CreateModel(
            name='SchemaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('locked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeoAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_meta', models.BooleanField(default=True, help_text='Auto-generate meta title/description/canonical when missing.')),
                ('auto_tags', models.BooleanField(default=True, help_text='Auto-extract tags from title/summary/body and attach to posts.')),
                ('auto_schema', models.BooleanField(default=True, help_text='Generate JSON-LD (Article/Breadcrumb) for posts.')),
                ('suggest_only', models.BooleanField(default=False, help_text='If true, only suggest tags; do not auto-attach.')),
                ('tag_sitemap_enabled', models.BooleanField(default=True, help_text='Expose tag sitemap section when tags are public.')),
                ('comment_nofollow', models.BooleanField(default=True, help_text="Add rel='nofollow ugc' to comment links.")),
                ('comment_bump_lastmod', models.BooleanField(default=True, help_text='Update lastmod for posts/pages when new comments land.')),
            ],
            options={
                'verbose_name': 'SEO Automation Settings',
                'db_table': 'seo_seoautomationsettings',
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_enabled', models.BooleanField(default=True)),
                ('auto_meta_enabled', models.BooleanField(default=False)),
                ('auto_schema_enabled', models.BooleanField(default=False)),
                ('auto_linking_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True)),
                ('lastmod', models.DateTimeField(blank=True, null=True)),
                ('changefreq', models.CharField(blank=True, default='', max_length=20)),
                ('priority', models.FloatField(default=0.5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkableEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('entity_type', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.URLField()),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('vector', models.BinaryField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='LinkSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0.0)),
                ('is_applied', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_from', to='seo.linkableentity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_to', to='seo.linkableentity')),
            ],
        ),
        migrations.CreateModel(
            name='SEOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('locked', models.BooleanField(default=False)),
                ('ai_generated', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
