# Generated by hand for Week 17 SEO engine upgrades

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="metadata",
            name="auto_apply_suggestions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="metadata",
            name="proposed_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="BatchOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("audit", "Audit"),
                            ("metadata", "Metadata"),
                            ("interlink", "Interlink"),
                            ("knowledge_graph", "Knowledge Graph"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seo_batch_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Batch Operation",
                "verbose_name_plural": "SEO Batch Operations",
                "db_table": "seo_batchoperation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterlinkExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phrase", models.CharField(max_length=255)),
                (
                    "source_pattern",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "target_pattern",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Interlink Exclusion",
                "verbose_name_plural": "Interlink Exclusions",
                "db_table": "seo_interlinkexclusion",
                "ordering": ["phrase"],
                "unique_together": {("phrase", "source_pattern", "target_pattern")},
            },
        ),
        migrations.CreateModel(
            name="SeoEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "entity_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("source_object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seo_entities",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Entity",
                "verbose_name_plural": "SEO Entities",
                "db_table": "seo_seoentity",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["entity_type", "is_active"], name="seo_seoent_entity__28384a_idx")],
            },
        ),
        migrations.CreateModel(
            name="SeoKeywordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("keyword", models.CharField(db_index=True, max_length=255)),
                ("target_url", models.URLField(blank=True, default="")),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("search_volume", models.PositiveIntegerField(default=0)),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("informational", "Informational"),
                            ("transactional", "Transactional"),
                            ("navigational", "Navigational"),
                            ("commercial", "Commercial"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, default="manual", max_length=100)),
            ],
            options={
                "verbose_name": "SEO Keyword History",
                "verbose_name_plural": "SEO Keyword History",
                "db_table": "seo_seokeywordhistory",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeoEntityEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("relation_type", models.CharField(db_index=True, max_length=100)),
                ("weight", models.FloatField(default=0.0)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="seo.seoentity",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="seo.seoentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Entity Edge",
                "verbose_name_plural": "SEO Entity Edges",
                "db_table": "seo_seoentityedge",
                "ordering": ["-weight", "-created_at"],
                "unique_together": {("source", "target", "relation_type")},
            },
        ),
    ]
