# Generated by Django 5.2.12 on 2026-04-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_week17_seo_engine'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seoentity',
            new_name='seo_seoenti_entity__244110_idx',
            old_name='seo_seoent_entity__28384a_idx',
        ),
    ]
