# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('blog', '0001_initial'),
        ('firmwares', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreative',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adevent',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.adcreative'),
        ),
        migrations.AddField(
            model_name='adevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adnetwork',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adnetwork',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adnetwork',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adevent',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.adplacement'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adunit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adunit',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_units', to='ads.adnetwork'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateclick',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='affiliate_links', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='target_brands',
            field=models.ManyToManyField(blank=True, help_text='Show this product on these brand pages.', related_name='affiliate_products', to='firmwares.brand'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='target_models',
            field=models.ManyToManyField(blank=True, help_text='Show this product on these model pages.', related_name='affiliate_products', to='firmwares.model'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateclick',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to='ads.affiliateproduct'),
        ),
        migrations.AddField(
            model_name='affiliateproductcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ads.affiliateproductcategory'),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ads.affiliateproductcategory'),
        ),
        migrations.AddField(
            model_name='affiliateproductmatch',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='blog.post'),
        ),
        migrations.AddField(
            model_name='affiliateproductmatch',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='firmwares.brand'),
        ),
        migrations.AddField(
            model_name='affiliateproductmatch',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='firmwares.model'),
        ),
        migrations.AddField(
            model_name='affiliateproductmatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ads.affiliateproduct'),
        ),
        migrations.AddField(
            model_name='affiliateproductmatch',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='firmwares.variant'),
        ),
        migrations.AddField(
            model_name='affiliateprovider',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateprovider',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateprovider',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateproduct',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ads.affiliateprovider'),
        ),
        migrations.AddField(
            model_name='affiliateclick',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to='ads.affiliateprovider'),
        ),
        migrations.AddField(
            model_name='affiliatesource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatesource',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatesource',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='ads.affiliatesource'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adevent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.campaign'),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='ads.campaign'),
        ),
        migrations.AddField(
            model_name='placementassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placementassignment',
            name='creative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ads.adcreative'),
        ),
        migrations.AddField(
            model_name='placementassignment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placementassignment',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ads.adplacement'),
        ),
        migrations.AddField(
            model_name='placementassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardedadconfig',
            name='ad_unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'ad_format': 'rewarded'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.adunit'),
        ),
        migrations.AddField(
            model_name='rewardedadconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardedadconfig',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardedadconfig',
            name='network',
            field=models.ForeignKey(blank=True, limit_choices_to={'supports_rewarded': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.adnetwork'),
        ),
        migrations.AddField(
            model_name='rewardedadconfig',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewarded_configs', to='ads.adplacement'),
        ),
        migrations.AddField(
            model_name='rewardedadconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardedadview',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='ads.rewardedadconfig'),
        ),
        migrations.AddField(
            model_name='rewardedadview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewarded_ad_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='adunit',
            unique_together={('network', 'unit_id')},
        ),
        migrations.AddIndex(
            model_name='affiliateproduct',
            index=models.Index(fields=['asin'], name='ads_affilia_asin_a22efe_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateproduct',
            index=models.Index(fields=['product_type', 'is_enabled'], name='ads_affilia_product_e688cc_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateproduct',
            index=models.Index(fields=['is_universal', 'is_enabled'], name='ads_affilia_is_univ_a7c4fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliateproduct',
            unique_together={('provider', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['product', 'created_at'], name='ads_affilia_product_b6cffc_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['provider', 'created_at'], name='ads_affilia_provide_02e8d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliatelink',
            unique_together={('source', 'name')},
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['event_type', 'created_at'], name='ads_adevent_event_t_1f6b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['campaign'], name='ads_adevent_campaig_c23862_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='placementassignment',
            unique_together={('placement', 'creative')},
        ),
        migrations.AddIndex(
            model_name='rewardedadview',
            index=models.Index(fields=['user', 'created_at'], name='ads_rewarde_user_id_14dd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardedadview',
            index=models.Index(fields=['config', 'status'], name='ads_rewarde_config__75bb3f_idx'),
        ),
    ]
