# Generated by Django 5.2.12 on 2026-03-26 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_adevent_campaign_alter_adevent_creative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoadsscanresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Auto-Ads Scan Result', 'verbose_name_plural': 'Auto-Ads Scan Results'},
        ),
        migrations.AddField(
            model_name='autoadsscanresult',
            name='ad_density_warning',
            field=models.BooleanField(default=False, help_text='True if template already has high ad density.'),
        ),
        migrations.AddField(
            model_name='autoadsscanresult',
            name='estimated_traffic',
            field=models.CharField(choices=[('high', 'High Traffic'), ('medium', 'Medium Traffic'), ('low', 'Low Traffic')], default='medium', help_text='Estimated traffic level for this template.', max_length=10),
        ),
        migrations.AddField(
            model_name='autoadsscanresult',
            name='extends_chain',
            field=models.JSONField(default=list, help_text='Template inheritance chain (extends/includes).'),
        ),
        migrations.AddField(
            model_name='autoadsscanresult',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('partial', 'Partially Approved'), ('rejected', 'Rejected'), ('excluded', 'Template Excluded')], db_index=True, default='pending', help_text='Admin review status for this scan result.', max_length=20),
        ),
        migrations.AddField(
            model_name='autoadsscanresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoadsscanresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_reviewed_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoadsscanresult',
            name='template_type',
            field=models.CharField(choices=[('page', 'Static Page'), ('list', 'List / Index'), ('detail', 'Detail / Single'), ('search', 'Search Results'), ('utility', 'Utility / Form'), ('component', 'Component / Partial')], default='page', help_text='Auto-classified template type.', max_length=20),
        ),
        migrations.AddField(
            model_name='autoadsscanresult',
            name='total_discoveries',
            field=models.PositiveIntegerField(default=0, help_text='Number of individual placement discoveries from this scan.'),
        ),
        migrations.AddField(
            model_name='autoadsscanresult',
            name='viewport_zones',
            field=models.JSONField(default=list, help_text='Detected viewport zones (above-fold, sidebar, mid-content, etc.).'),
        ),
        migrations.AlterField(
            model_name='autoadsscanresult',
            name='template_path',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name='autoadsscanresult',
            table='ads_autoadsscanresult',
        ),
        migrations.CreateModel(
            name='ScanDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_code', models.CharField(help_text='Proposed placement code (e.g. blog-post-detail-sidebar-top).', max_length=120)),
                ('placement_name', models.CharField(max_length=200)),
                ('zone', models.CharField(blank=True, default='', help_text='Viewport zone: above-fold, mid-content, sidebar, footer, sticky.', max_length=60)),
                ('allowed_types', models.CharField(default='banner,native,html', max_length=100)),
                ('allowed_sizes', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, help_text='Confidence score 0–100 for this specific placement.', max_digits=5)),
                ('rationale', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('placement', models.ForeignKey(blank=True, help_text='Created AdPlacement after approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_source_discovery', to='ads.adplacement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_reviewed_discoveries', to=settings.AUTH_USER_MODEL)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='ads.autoadsscanresult')),
            ],
            options={
                'verbose_name': 'Scan Discovery',
                'verbose_name_plural': 'Scan Discoveries',
                'db_table': 'ads_scandiscovery',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAdExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_path', models.CharField(db_index=True, help_text='Template path relative to templates/ root.', max_length=255, unique=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Why this template is excluded from ads.')),
                ('excluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_template_exclusions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Ad Exclusion',
                'verbose_name_plural': 'Template Ad Exclusions',
                'db_table': 'ads_templateadexclusion',
                'ordering': ['template_path'],
            },
        ),
    ]
