# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('devto', 'Dev.to'), ('hashnode', 'Hashnode'), ('medium', 'Medium'), ('gist', 'GitHub Gist'), ('mailchimp', 'Mailchimp'), ('sendgrid', 'SendGrid'), ('substack', 'Substack'), ('google_indexing', 'Google Indexing API'), ('bing_indexing', 'Bing URL Submit'), ('chatgpt_action', 'ChatGPT Action'), ('gemini', 'Google Gemini'), ('copilot', 'Bing Copilot'), ('rss', 'RSS'), ('atom', 'Atom'), ('json', 'JSON Feed'), ('websub', 'WebSub')], max_length=64)),
                ('variant_type', models.CharField(choices=[('summary', 'Summary'), ('caption', 'Caption'), ('tags', 'Hashtags/Tags'), ('image_prompt', 'Image prompt'), ('thread', 'Thread/long-form'), ('email', 'Email')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_enabled', models.BooleanField(default=True, help_text='Master switch: Enable/disable all content distribution globally.')),
                ('auto_fanout_on_publish', models.BooleanField(default=True, help_text='Automatically queue distribution when blog posts are published. Disable for manual control.')),
                ('default_channels', models.JSONField(blank=True, default=list, help_text="Default channels for auto-distribution (empty = use all active channels). Example: ['twitter', 'facebook', 'linkedin']")),
                ('max_platforms_per_content', models.PositiveIntegerField(default=5, help_text='⚠️ CRITICAL: Maximum platforms to distribute to simultaneously. Recommended: 5 or less to avoid spam detection. Higher values risk platform bans.')),
                ('distribution_frequency_hours', models.PositiveIntegerField(default=4, help_text='Minimum hours between auto-distributions for same content. Prevents spam. Recommended: 4-24 hours.')),
                ('max_seo_title_length', models.PositiveIntegerField(default=60, help_text='Maximum characters for SEO titles. Google displays ~60 chars. Longer titles get truncated in search results.')),
                ('max_seo_description_length', models.PositiveIntegerField(default=160, help_text='Maximum characters for meta descriptions. Google displays ~160 chars. Keep it concise for better CTR.')),
                ('max_seo_tags', models.PositiveIntegerField(default=10, help_text='⚠️ Maximum SEO-focused tags per content. Too many tags = keyword stuffing = Google penalty. Recommended: 5-10.')),
                ('max_auto_tags', models.PositiveIntegerField(default=15, help_text='⚠️ Maximum auto-generated tags per post. Over-tagging reduces content quality. Recommended: 10-15. Platform limits apply.')),
                ('auto_tag_frequency_days', models.PositiveIntegerField(default=7, help_text='How often (in days) to regenerate auto-tags for existing content. Lower = more frequent updates. 0 = never update.')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum retry attempts per failed distribution job before marking as permanently failed.')),
                ('retry_backoff_seconds', models.PositiveIntegerField(default=1800, help_text='Wait time (seconds) before retrying a failed job. 1800s = 30 minutes. Use exponential backoff for rate limits.')),
                ('allow_indexing_jobs', models.BooleanField(default=False, help_text='Allow automatic submission to search engines (Google/Bing indexing APIs). Requires API keys. Disable if not configured.')),
                ('require_admin_approval', models.BooleanField(default=False, help_text='Require manual admin approval before executing distribution jobs. Good for auditing but slows automation.')),
                ('enable_firmware_auto_distribution', models.BooleanField(default=True, help_text='Auto-distribute firmware blog posts when created/updated. Disable to distribute firmware posts manually only.')),
            ],
            options={
                'verbose_name': 'Distribution Settings',
                'verbose_name_plural': 'Distribution Settings',
            },
        ),
        migrations.CreateModel(
            name='ShareJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('devto', 'Dev.to'), ('hashnode', 'Hashnode'), ('medium', 'Medium'), ('gist', 'GitHub Gist'), ('mailchimp', 'Mailchimp'), ('sendgrid', 'SendGrid'), ('substack', 'Substack'), ('google_indexing', 'Google Indexing API'), ('bing_indexing', 'Bing URL Submit'), ('chatgpt_action', 'ChatGPT Action'), ('gemini', 'Google Gemini'), ('copilot', 'Bing Copilot'), ('rss', 'RSS'), ('atom', 'Atom'), ('json', 'JSON Feed'), ('websub', 'WebSub')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('external_post_id', models.CharField(blank=True, default='', max_length=200)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=16)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('response_code', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.JSONField(blank=True, default=list, help_text='List of channel identifiers')),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('devto', 'Dev.to'), ('hashnode', 'Hashnode'), ('medium', 'Medium'), ('gist', 'GitHub Gist'), ('mailchimp', 'Mailchimp'), ('sendgrid', 'SendGrid'), ('substack', 'Substack'), ('google_indexing', 'Google Indexing API'), ('bing_indexing', 'Bing URL Submit'), ('chatgpt_action', 'ChatGPT Action'), ('gemini', 'Google Gemini'), ('copilot', 'Bing Copilot'), ('rss', 'RSS'), ('atom', 'Atom'), ('json', 'JSON Feed'), ('websub', 'WebSub')], max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('body_template', models.TextField(help_text='Use placeholders: {title}, {url}, {summary}, {hashtags}')),
                ('media_template', models.TextField(blank=True, default='')),
                ('ai_prompt', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['channel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook Pages'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('devto', 'Dev.to'), ('hashnode', 'Hashnode'), ('medium', 'Medium'), ('gist', 'GitHub Gist'), ('mailchimp', 'Mailchimp'), ('sendgrid', 'SendGrid'), ('substack', 'Substack'), ('google_indexing', 'Google Indexing API'), ('bing_indexing', 'Bing URL Submit'), ('chatgpt_action', 'ChatGPT Action'), ('gemini', 'Google Gemini'), ('copilot', 'Bing Copilot'), ('rss', 'RSS'), ('atom', 'Atom'), ('json', 'JSON Feed'), ('websub', 'WebSub')], max_length=64)),
                ('account_name', models.CharField(blank=True, default='', max_length=200)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['channel', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='SyndicationPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('endpoint', models.URLField()),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('token', 'Token'), ('basic', 'Basic'), ('api_key', 'API Key')], default='none', max_length=32)),
                ('format', models.CharField(choices=[('rss', 'RSS'), ('json', 'JSON Feed'), ('api', 'Custom API'), ('graphql', 'GraphQL')], default='rss', max_length=32)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebSubSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_url', models.URLField()),
                ('hub_url', models.URLField()),
                ('secret', models.CharField(blank=True, default='', max_length=200)),
                ('lease_seconds', models.PositiveIntegerField(default=864000)),
                ('active', models.BooleanField(default=True)),
                ('last_challenge_at', models.DateTimeField(blank=True, null=True)),
                ('last_pinged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('content_url', models.URLField(blank=True, default='')),
                ('target_channels', models.JSONField(blank=True, default=list, help_text='List of channels to distribute to (twitter, linkedin, facebook, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('distributing', 'Distributing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(default=5, help_text='1=highest, 10=lowest')),
                ('schedule_at', models.DateTimeField(blank=True, help_text='Schedule distribution for later', null=True)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('distribution_count', models.PositiveIntegerField(default=0, help_text='Number of successful distributions')),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional distribution metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Distribution',
                'verbose_name_plural': 'Content Distributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
