# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_initial'),
        ('distribution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdistribution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentvariant',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentvariant',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='blog.post'),
        ),
        migrations.AddField(
            model_name='sharejob',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_jobs', to='blog.post'),
        ),
        migrations.AddField(
            model_name='sharelog',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='distribution.sharejob'),
        ),
        migrations.AddField(
            model_name='shareplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareplan',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_plans', to='blog.post'),
        ),
        migrations.AddField(
            model_name='sharejob',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='distribution.shareplan'),
        ),
        migrations.AlterUniqueTogether(
            name='sharetemplate',
            unique_together={('channel', 'name')},
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharejob',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='distribution.socialaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='websubsubscription',
            unique_together={('topic_url', 'hub_url')},
        ),
        migrations.AddIndex(
            model_name='contentdistribution',
            index=models.Index(fields=['content_type', 'object_id'], name='distributio_content_a873d0_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdistribution',
            index=models.Index(fields=['status', 'schedule_at'], name='distributio_status_c2ca8b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdistribution',
            index=models.Index(fields=['priority', 'created_at'], name='distributio_priorit_a988b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentvariant',
            unique_together={('post', 'channel', 'variant_type')},
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('channel', 'account_name')},
        ),
        migrations.AddIndex(
            model_name='sharejob',
            index=models.Index(fields=['channel', 'status'], name='distributio_channel_b266e5_idx'),
        ),
        migrations.AddIndex(
            model_name='sharejob',
            index=models.Index(fields=['schedule_at'], name='distributio_schedul_00fc93_idx'),
        ),
    ]
