# Generated by Django 5.2.12 on 2026-03-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentvariant',
            name='variant_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('caption', 'Caption'), ('tags', 'Hashtags/Tags'), ('image_prompt', 'Image prompt'), ('video_script', 'Video script'), ('thread', 'Thread/long-form'), ('email', 'Email')], max_length=32),
        ),
    ]
