# Generated by Django 5.2.12 on 2026-03-26 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_ad_gate_config_post_ad_gate_enabled_and_more'),
        ('distribution', '0003_alter_contentvariant_variant_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube (16:9 landscape)'), ('youtube_shorts', 'YouTube Shorts (9:16 vertical)'), ('tiktok', 'TikTok (9:16 vertical)'), ('instagram_reels', 'Instagram Reels (9:16 vertical)'), ('facebook', 'Facebook (16:9 landscape)'), ('linkedin', 'LinkedIn (16:9 landscape)'), ('twitter', 'Twitter/X (16:9 landscape)')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('processing', 'Post-Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('publishing', 'Publishing'), ('published', 'Published')], default='queued', max_length=20)),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape (16:9)'), ('portrait', 'Portrait (9:16)'), ('square', 'Square (1:1)')], default='landscape', max_length=16)),
                ('video_file', models.FileField(blank=True, default='', help_text='Rendered MP4 video file.', upload_to='generated_videos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, default='', help_text='Auto-generated thumbnail from video.', upload_to='generated_videos/thumbs/%Y/%m/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('fps', models.PositiveIntegerField(default=30)),
                ('script_data', models.JSONField(blank=True, default=dict, help_text='AI-generated script: title, hook, scenes[], cta, hashtags.')),
                ('style_config', models.JSONField(blank=True, default=dict, help_text='MrBeast-style config: transitions, text_style, music_mood, pacing.')),
                ('publish_queued', models.BooleanField(default=False, help_text='If True, auto-publish to platform once rendering completes.')),
                ('published_url', models.URLField(blank=True, default='', help_text='URL on the platform after successful upload.')),
                ('external_id', models.CharField(blank=True, default='', help_text='Platform video ID (YouTube video ID, TikTok post ID, etc.).', max_length=200)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendered_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_videos', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_videos', to='blog.post')),
            ],
            options={
                'verbose_name': 'Generated Video',
                'verbose_name_plural': 'Generated Videos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='distributio_status_1886f3_idx'), models.Index(fields=['platform', 'status'], name='distributio_platfor_a586e2_idx')],
                'unique_together': {('post', 'platform')},
            },
        ),
    ]
