# Generated by Django 5.2.12 on 2026-03-23 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tier_level', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=12)),
                ('description', models.TextField(blank=True, default='')),
                ('badge_color', models.CharField(default='blue', help_text='Tailwind color for badge (blue, emerald, purple, amber, red)', max_length=20)),
                ('badge_icon', models.CharField(default='package', help_text='Lucide icon name for tier badge', max_length=50)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_quarterly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_lifetime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price in platform credits (0 = not purchasable with credits)', max_digits=10)),
                ('trial_days', models.PositiveSmallIntegerField(default=0, help_text='Trial period in days (0 = no trial)')),
                ('daily_download_limit', models.IntegerField(default=5, help_text='Max downloads per 24h (-1 = unlimited)')),
                ('monthly_download_limit', models.IntegerField(default=50, help_text='Max downloads per month (-1 = unlimited)')),
                ('max_file_size_mb', models.IntegerField(default=500, help_text='Max single file size in MB (-1 = unlimited)')),
                ('daily_bandwidth_mb', models.IntegerField(default=2048, help_text='Max bandwidth per 24h in MB (-1 = unlimited)')),
                ('monthly_bandwidth_mb', models.IntegerField(default=20480, help_text='Max bandwidth per month in MB (-1 = unlimited)')),
                ('max_download_speed_kbps', models.IntegerField(default=0, help_text='Speed cap in KB/s (0 = no limit)')),
                ('max_concurrent_downloads', models.PositiveSmallIntegerField(default=1, help_text='Max simultaneous downloads')),
                ('ad_free', models.BooleanField(default=False, help_text='Skip ad gates before download')),
                ('priority_queue', models.BooleanField(default=False, help_text='Priority download queue (server-side)')),
                ('resume_support', models.BooleanField(default=True, help_text='Allow download resume after interruption')),
                ('api_access', models.BooleanField(default=False, help_text='Allow firmware downloads via API')),
                ('early_access', models.BooleanField(default=False, help_text='Access to new firmware before public release')),
                ('direct_links', models.BooleanField(default=False, help_text='Generate direct download links (no redirect)')),
                ('access_official', models.BooleanField(default=True, help_text='Official firmware')),
                ('access_engineering', models.BooleanField(default=False, help_text='Engineering/test firmware')),
                ('access_readback', models.BooleanField(default=False, help_text='Readback / dump firmware')),
                ('access_modified', models.BooleanField(default=False, help_text='Modified / custom ROM')),
                ('cooldown_seconds', models.PositiveIntegerField(default=60, help_text='Wait time between downloads in seconds (0 = no cooldown)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Assign to new users automatically (only one should be default)')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight on pricing page')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('extra_features', models.JSONField(blank=True, default=dict, help_text='Additional feature flags as key-value pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package Tier',
                'verbose_name_plural': 'Package Tiers',
                'db_table': 'shop_packagetier',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('firmware', 'Firmware'), ('subscription', 'Subscription'), ('token_pack', 'Token Pack'), ('service', 'Service'), ('package', 'Package')], max_length=15),
        ),
        migrations.CreateModel(
            name='PackageQuotaOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_download_limit', models.IntegerField(blank=True, help_text='Override daily limit (null = use tier)', null=True)),
                ('monthly_download_limit', models.IntegerField(blank=True, help_text='Override monthly limit (null = use tier)', null=True)),
                ('daily_bandwidth_mb', models.IntegerField(blank=True, help_text='Override daily bandwidth (null = use tier)', null=True)),
                ('monthly_bandwidth_mb', models.IntegerField(blank=True, help_text='Override monthly bandwidth (null = use tier)', null=True)),
                ('max_download_speed_kbps', models.IntegerField(blank=True, help_text='Override speed cap (null = use tier)', null=True)),
                ('max_concurrent_downloads', models.PositiveSmallIntegerField(blank=True, help_text='Override concurrency (null = use tier)', null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_quota_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_quota_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package Quota Override',
                'verbose_name_plural': 'Package Quota Overrides',
                'db_table': 'shop_packagequotaoverride',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=12)),
                ('downloads_today', models.PositiveIntegerField(default=0)),
                ('downloads_this_month', models.PositiveIntegerField(default=0)),
                ('bandwidth_today_mb', models.PositiveIntegerField(default=0)),
                ('bandwidth_this_month_mb', models.PositiveIntegerField(default=0)),
                ('last_download_at', models.DateTimeField(blank=True, null=True)),
                ('usage_reset_date', models.DateField(blank=True, help_text='Next monthly usage counter reset', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, default='', help_text='Payment gateway ref', max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_packages', to='shop.packagetier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Package',
                'verbose_name_plural': 'User Packages',
                'db_table': 'shop_userpackage',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='userpkg_user_status_idx')],
            },
        ),
    ]
