# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ai.workflow'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['status'], name='ai_pipeline_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['started_at'], name='ai_pipeline_started_idx'),
        ),
    ]
