# Generated by Django 5.2.12 on 2026-03-24 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('total_searches', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('new_blog_posts', models.PositiveIntegerField(default=0)),
                ('new_firmwares', models.PositiveIntegerField(default=0)),
                ('avg_page_load_time', models.FloatField(default=0.0)),
                ('avg_api_response_time', models.FloatField(default=0.0)),
                ('top_pages', models.JSONField(blank=True, default=list)),
                ('top_searches', models.JSONField(blank=True, default=list)),
                ('top_downloads', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Metrics',
                'db_table': 'analytics_daily_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('page_views_last_hour', models.PositiveIntegerField(default=0)),
                ('downloads_last_hour', models.PositiveIntegerField(default=0)),
                ('searches_last_hour', models.PositiveIntegerField(default=0)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('top_pages_now', models.JSONField(blank=True, default=list)),
                ('active_downloads', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Realtime Metrics',
                'db_table': 'analytics_realtime_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('total_uploads', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_likes_given', models.PositiveIntegerField(default=0)),
                ('total_likes_received', models.PositiveIntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('days_active', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('favorite_brands', models.JSONField(blank=True, default=list)),
                ('favorite_categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Analytics',
                'db_table': 'analytics_user_analytics',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('download', 'Download'), ('search', 'Search'), ('share', 'Share'), ('like', 'Like'), ('comment', 'Comment'), ('signup', 'Signup'), ('login', 'Login'), ('upload', 'Upload'), ('custom', 'Custom')], db_index=True, max_length=50)),
                ('event_name', models.CharField(max_length=200)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='event_type_idx'), models.Index(fields=['user', '-created_at'], name='event_user_idx'), models.Index(fields=['content_type', 'object_id'], name='event_content_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_pageview',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', '-created_at'], name='pageview_path_idx'), models.Index(fields=['user', '-created_at'], name='pageview_user_idx'), models.Index(fields=['-created_at'], name='pageview_created_idx')],
            },
        ),
    ]
