# Generated by Django 5.2.12 on 2026-03-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Public contact email for footer/legal', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='', help_text='Footer copyright text (leave blank for auto: © {year} {site_name})', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_notifications',
            field=models.BooleanField(default=True, help_text='Enable in-app and push notifications'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_signup',
            field=models.BooleanField(default=True, help_text='Allow new user registration'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='GA4 Measurement ID (G-XXXX)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, default='', help_text='GTM container ID (GTM-XXXX)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Default Open Graph share image (1200x630 recommended)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(blank=True, default='', help_text='Canonical base URL (e.g. https://example.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_facebook',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_github',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_linkedin',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_telegram',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_twitter',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_youtube',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', help_text='Twitter @handle for twitter:site card (without @)', max_length=50),
        ),
    ]
