# Generated by Django 5.2.12 on 2026-03-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bounty_base_reward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default credit reward for fulfilling a firmware bounty', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='credit_to_currency_rate',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Exchange rate: 1 credit = X USD (for payout calculations)', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='daily_login_reward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credits awarded for daily login streak', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='download_cost_credits',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credits deducted per firmware download (0 = free)', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_payout_credits',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Minimum credit balance required to request a payout', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='profile_completion_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credits awarded when user completes their profile', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referee_bonus_credits',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credits awarded to referred user (referee) as welcome bonus', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referral_reward_credits',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credits awarded to referrer when referee completes signup', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='signup_bonus_credits',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Credits awarded to new users upon registration', max_digits=10),
        ),
    ]
