# Generated by Django 5.2.12 on 2026-03-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_bounty_base_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gsmarena_scrape_interval_hours',
            field=models.PositiveIntegerField(default=0, help_text='Auto-scrape GSMArena every N hours (0 = disabled, manual only)'),
        ),
    ]
