# Generated by Django 5.2.12 on 2026-03-21 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_gsmarena_scrape_interval_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='download_ad_gate_enabled',
            field=models.BooleanField(default=False, help_text='Require users to complete ad gate before downloading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='download_ad_gate_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Seconds user must watch ad before gate unlocks', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='download_countdown_seconds',
            field=models.PositiveIntegerField(default=10, help_text='Countdown seconds before download link appears (0 = instant)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='download_gate_enabled',
            field=models.BooleanField(default=True, help_text='Enable the download gate system (countdown + ad gate + token validation)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='download_hotlink_protection',
            field=models.BooleanField(default=True, help_text='Block direct linking from external sites'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='download_link_encryption',
            field=models.BooleanField(default=True, help_text='Use encrypted/signed tokens instead of direct file URLs'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='download_max_per_day',
            field=models.PositiveIntegerField(default=0, help_text='Max downloads per user per day (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='download_require_login',
            field=models.BooleanField(default=False, help_text='Require user login before downloading firmware'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='download_token_expiry_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutes before a download token expires', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
