# Generated by Django 5.2.12 on 2026-03-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitesettings_download_ad_gate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='multi_source_scrape_interval_hours',
            field=models.PositiveIntegerField(default=0, help_text='Auto-scrape ALL registered sources every N hours (0 = disabled, manual only). Runs independently from GSMArena.'),
        ),
    ]
