# Generated by Django 5.2.12 on 2026-03-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdownloadsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='serviceaccountquotalog',
            unique_together={('service_account', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceaccount',
            unique_together={('shared_drive', 'email')},
        ),
        migrations.AddIndex(
            model_name='firmwarestoragelocation',
            index=models.Index(fields=['content_type', 'object_id'], name='storage_fir_content_272857_idx'),
        ),
        migrations.AddIndex(
            model_name='firmwarestoragelocation',
            index=models.Index(fields=['storage_type', 'is_primary'], name='storage_fir_storage_98c131_idx'),
        ),
        migrations.AddIndex(
            model_name='firmwarestoragelocation',
            index=models.Index(fields=['gdrive_file_id'], name='storage_fir_gdrive__bd85a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='drivefileorganization',
            unique_together={('shared_drive', 'brand_name', 'model_name', 'variant_name', 'category_name')},
        ),
        migrations.AddIndex(
            model_name='userdownloadsession',
            index=models.Index(fields=['user', 'status'], name='storage_use_user_id_de6949_idx'),
        ),
        migrations.AddIndex(
            model_name='userdownloadsession',
            index=models.Index(fields=['expires_at'], name='storage_use_expires_0b9315_idx'),
        ),
        migrations.AddIndex(
            model_name='userdownloadsession',
            index=models.Index(fields=['status', 'expires_at'], name='storage_use_status_0724c7_idx'),
        ),
    ]
