# Generated by Django 5.2.12 on 2026-04-14 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccountquotalog',
            name='service_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_logs', to='storage.serviceaccount'),
        ),
        migrations.AlterField(
            model_name='userdownloadsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_download_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
