# Generated by Django 5.2.12 on 2026-03-18 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        ('firmwares', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_version_wanted', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed'), ('expired', 'Expired')], db_index=True, default='open', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bounty Request',
                'verbose_name_plural': 'Bounty Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('status', models.CharField(choices=[('holding', 'Holding'), ('released', 'Released'), ('refunded', 'Refunded')], default='holding', max_length=10)),
                ('wallet_reference', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='bounty.bountyrequest')),
            ],
            options={
                'verbose_name': 'Bounty Escrow',
            },
        ),
        migrations.CreateModel(
            name='BountySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('firmware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firmwares.officialfirmware')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='bounty.bountyrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bounty Submission',
                'verbose_name_plural': 'Bounty Submissions',
                'ordering': ['-created_at'],
                'unique_together': {('request', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FraudCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='0-100; higher = more suspicious')),
                ('flags', models.JSONField(blank=True, default=list)),
                ('passed', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_check', to='bounty.bountysubmission')),
            ],
            options={
                'verbose_name': 'Fraud Check',
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('needs_more', 'Needs More Info')], max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='bounty.bountysubmission')),
            ],
            options={
                'verbose_name': 'Peer Review',
                'verbose_name_plural': 'Peer Reviews',
                'unique_together': {('submission', 'reviewer')},
            },
        ),
    ]
