# Generated by Django 5.2.12 on 2026-03-22 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
        ('firmwares', '0011_brand_description_brand_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountyrequest',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_requests', to='firmwares.brand'),
        ),
        migrations.AddField(
            model_name='bountyrequest',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_requests', to='firmwares.model'),
        ),
        migrations.AddField(
            model_name='bountyrequest',
            name='request_type',
            field=models.CharField(choices=[('firmware', 'Firmware Request'), ('support', 'Support / Troubleshooting')], db_index=True, default='firmware', max_length=20),
        ),
        migrations.AddField(
            model_name='bountyrequest',
            name='resolution_note',
            field=models.TextField(blank=True, default='', help_text="Technician's note on how the issue was resolved."),
        ),
        migrations.AddField(
            model_name='bountyrequest',
            name='resolution_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('single', 'Single Contributor'), ('multiple', 'Multiple Contributors'), ('self_with_ideas', 'Self-Resolved (Community Ideas)')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bountyrequest',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bountyrequest',
            name='what_tried',
            field=models.TextField(blank=True, default='', help_text='For support requests: what you have already tried.'),
        ),
        migrations.AddField(
            model_name='bountysubmission',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Technician confirmed this solution helped resolve the issue.'),
        ),
        migrations.AlterField(
            model_name='bountyrequest',
            name='description',
            field=models.TextField(help_text='Describe what you need or the issue.'),
        ),
        migrations.AlterField(
            model_name='bountyrequest',
            name='fw_version_wanted',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bountysubmission',
            name='firmware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_submissions', to='firmwares.officialfirmware'),
        ),
    ]
