# Generated by Django 5.2.12 on 2026-03-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_bountyrequest_brand_bountyrequest_device_model_and_more'),
        ('forum', '0003_forumattachment_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountyrequest',
            name='forum_topic',
            field=models.ForeignKey(blank=True, help_text='Auto-linked forum discussion for this bounty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_requests', to='forum.forumtopic'),
        ),
    ]
