# Generated by Django 5.2.12 on 2026-04-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0003_bountyrequest_forum_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bountyescrow',
            options={'verbose_name': 'Bounty Escrow', 'verbose_name_plural': 'Bounty Escrows'},
        ),
        migrations.AlterModelOptions(
            name='fraudcheck',
            options={'verbose_name': 'Fraud Check', 'verbose_name_plural': 'Fraud Checks'},
        ),
    ]
