// This file is generated by FlutterFire CLI.
// Run: flutterfire configure
// Replace this placeholder with the generated file after running FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYZapgIc6wELPjc09Qr45nFplLg3u0biA',
    appId: '1:759926080214:web:43b9d432cc13e62bfe7f77',
    messagingSenderId: '759926080214',
    projectId: 'shoeserp-clean-20260327',
    authDomain: 'shoeserp-clean-20260327.firebaseapp.com',
    storageBucket: 'shoeserp-clean-20260327.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkuhoehQ8G7GBCx5Gun_v3KOlM2gqyBDg',
    appId: '1:759926080214:android:81679cd4f6df2b21fe7f77',
    messagingSenderId: '759926080214',
    projectId: 'shoeserp-clean-20260327',
    storageBucket: 'shoeserp-clean-20260327.firebasestorage.app',
  );
}
