# Generated by Django 5.2.12 on 2026-03-18 20:54

import apps.firmwares.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_quotatier_devicefingerprint_behaviorinsight_and_more'),
        ('firmwares', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotlinkBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('blocked_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotlink Block',
                'verbose_name_plural': 'Hotlink Blocks',
                'db_table': 'download_links_hotlinkblock',
                'ordering': ['-blocked_count'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=10)),
                ('devices_checked', models.PositiveIntegerField(default=0)),
                ('devices_updated', models.PositiveIntegerField(default=0)),
                ('devices_created', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync Run',
                'verbose_name_plural': 'Sync Runs',
                'db_table': 'gsmarena_sync_syncrun',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('bytes_delivered', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='started', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download Session',
                'verbose_name_plural': 'Download Sessions',
                'db_table': 'download_links_downloadsession',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AdGateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('video', 'Video'), ('banner', 'Banner'), ('interstitial', 'Interstitial')], default='video', max_length=20)),
                ('ad_network', models.CharField(blank=True, default='', max_length=50)),
                ('watched_seconds', models.PositiveSmallIntegerField(default=0)),
                ('required_seconds', models.PositiveSmallIntegerField(default=30)),
                ('credits_earned', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_logs', to='firmwares.downloadsession')),
            ],
            options={
                'verbose_name': 'Ad Gate Log',
                'verbose_name_plural': 'Ad Gate Logs',
                'db_table': 'download_links_adgatelog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.firmwares.models._gen_token, max_length=64, unique=True)),
                ('ad_gate_required', models.BooleanField(default=True)),
                ('ad_gate_completed', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='firmwares.officialfirmware')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download Token',
                'verbose_name_plural': 'Download Tokens',
                'db_table': 'download_links_downloadtoken',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='downloadsession',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='firmwares.downloadtoken'),
        ),
        migrations.CreateModel(
            name='GSMArenaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsmarena_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('local_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gsmarena_records', to='devices.device')),
            ],
            options={
                'verbose_name': 'GSMArena Device',
                'verbose_name_plural': 'GSMArena Devices',
                'db_table': 'gsmarena_sync_gsmarenadevice',
                'ordering': ['brand', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='OEMSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('scraper_class', models.CharField(help_text='Python dotted path to scraper class', max_length=200)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('basic', 'Basic Auth')], default='none', max_length=10)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Auth credentials / config — store encrypted in production')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oem_sources', to='firmwares.brand')),
            ],
            options={
                'verbose_name': 'OEM Source',
                'verbose_name_plural': 'OEM Sources',
                'db_table': 'fw_scraper_oemsource',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_cron', models.CharField(default='0 2 * * *', max_length=50)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_config', to='firmwares.oemsource')),
            ],
            options={
                'verbose_name': 'Scraper Config',
                'verbose_name_plural': 'Scraper Configs',
                'db_table': 'fw_scraper_scraperconfig',
            },
        ),
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial — Some Errors'), ('failed', 'Failed')], db_index=True, default='running', max_length=10)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('items_ingested', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='firmwares.scraperconfig')),
            ],
            options={
                'verbose_name': 'Scraper Run',
                'verbose_name_plural': 'Scraper Runs',
                'db_table': 'fw_scraper_scraperrun',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped (Duplicate)')], db_index=True, default='pending', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fw_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to='firmwares.officialfirmware')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='firmwares.scraperrun')),
            ],
            options={
                'verbose_name': 'Ingestion Job',
                'verbose_name_plural': 'Ingestion Jobs',
                'db_table': 'fw_scraper_ingestionjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('local_value', models.TextField(blank=True, default='')),
                ('remote_value', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('keep_local', 'Keep Local'), ('use_remote', 'Use Remote'), ('manual', 'Manual')], default='pending', max_length=12)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('gsmarena_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='firmwares.gsmarenadevice')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='firmwares.syncrun')),
            ],
            options={
                'verbose_name': 'Sync Conflict',
                'verbose_name_plural': 'Sync Conflicts',
                'db_table': 'gsmarena_sync_syncconflict',
                'ordering': ['-run__started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedTester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_count', models.PositiveIntegerField(default=0, help_text='Firmwares verified')),
                ('avg_rating', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_tester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trusted Tester',
                'verbose_name_plural': 'Trusted Testers',
                'db_table': 'fw_verification_trustedtester',
            },
        ),
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('pass', 'Pass — Works'), ('partial', 'Partial — Issues Found'), ('fail', 'Fail — Bricked / Non-functional'), ('skip', 'Skip — Could Not Test')], max_length=10)),
                ('test_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reports', to='devices.device')),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_reports', to='firmwares.officialfirmware')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='firmwares.trustedtester')),
            ],
            options={
                'verbose_name': 'Verification Report',
                'verbose_name_plural': 'Verification Reports',
                'db_table': 'fw_verification_verificationreport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_earned', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_credits', to='firmwares.officialfirmware')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_credits', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='firmwares.verificationreport')),
            ],
            options={
                'verbose_name': 'Verification Credit',
                'verbose_name_plural': 'Verification Credits',
                'db_table': 'fw_verification_verificationcredit',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('skip', 'Skip')], max_length=6)),
                ('notes', models.TextField(blank=True, default='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='firmwares.verificationreport')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'db_table': 'fw_verification_testresult',
            },
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['token', 'status'], name='dl_token_status_idx'),
        ),
    ]
