# Generated by Django 5.2.12 on 2026-03-20 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('firmwares', '0004_absorb_changelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcreationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Brand Creation Request', 'verbose_name_plural': 'Brand Creation Requests'},
        ),
        migrations.AlterModelOptions(
            name='brandschema',
            options={'verbose_name': 'Brand Schema', 'verbose_name_plural': 'Brand Schemas'},
        ),
        migrations.AlterModelOptions(
            name='modelcreationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Model Creation Request', 'verbose_name_plural': 'Model Creation Requests'},
        ),
        migrations.AlterModelOptions(
            name='releasenote',
            options={'ordering': ['-id'], 'verbose_name': 'Release Note', 'verbose_name_plural': 'Release Notes'},
        ),
        migrations.AlterModelOptions(
            name='schemaupdateproposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Schema Update Proposal', 'verbose_name_plural': 'Schema Update Proposals'},
        ),
        migrations.AlterModelOptions(
            name='variantcreationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Variant Creation Request', 'verbose_name_plural': 'Variant Creation Requests'},
        ),
        migrations.AlterField(
            model_name='brandcreationrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_creation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brandcreationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_creation_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brandschema',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_brand_schemas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='engineeringfirmware',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelcreationrequest',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_creation_requests', to='firmwares.brand'),
        ),
        migrations.AlterField(
            model_name='modelcreationrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_creation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelcreationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_creation_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modifiedfirmware',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officialfirmware',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otherfirmware',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingfirmware',
            name='uploaded_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_firmwares_brand', to='firmwares.brand'),
        ),
        migrations.AlterField(
            model_name='pendingfirmware',
            name='uploaded_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_firmwares_model', to='firmwares.model'),
        ),
        migrations.AlterField(
            model_name='pendingfirmware',
            name='uploaded_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_firmwares_variant', to='firmwares.variant'),
        ),
        migrations.AlterField(
            model_name='pendingfirmware',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_firmwares_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readbackfirmware',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schemaupdateproposal',
            name='proposed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_proposals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schemaupdateproposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_proposal_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unclassifiedfirmware',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='variantcreationrequest',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_creation_requests', to='firmwares.model'),
        ),
        migrations.AlterField(
            model_name='variantcreationrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_creation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='variantcreationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_creation_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FirmwareDownloadAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('storage_session_id', models.UUIDField(blank=True, help_text='UserDownloadSession ID if applicable', null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('bytes_transferred', models.BigIntegerField(default=0, help_text='Actual bytes downloaded')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who attempted download', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firmwares_download_attempt',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-initiated_at'], name='firmwares_d_content_1f96be_idx'), models.Index(fields=['status', '-initiated_at'], name='firmwares_d_status_033ba7_idx'), models.Index(fields=['-initiated_at'], name='firmwares_d_initiat_168e80_idx')],
            },
        ),
        migrations.CreateModel(
            name='FirmwareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(blank=True, help_text='Requested variant (may not exist yet)', max_length=200)),
                ('firmware_type', models.CharField(choices=[('official', 'Official'), ('engineering', 'Engineering'), ('readback', 'Readback'), ('modified', 'Modified'), ('other', 'Other')], default='official', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details from user')),
                ('urgency', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=1, help_text='User-indicated urgency')),
                ('request_count', models.IntegerField(default=1, help_text='Number of users who requested this')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_requested_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('fulfilled_firmware_id', models.UUIDField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='firmwares.brand')),
                ('fulfilled_firmware_ct', models.ForeignKey(blank=True, help_text='Content type of firmware that fulfilled this', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='firmwares.model')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmware_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firmwares_request',
                'ordering': ['-request_count', '-last_requested_at'],
                'indexes': [models.Index(fields=['status', '-request_count'], name='firmwares_r_status_be7606_idx'), models.Index(fields=['brand', 'model', 'status'], name='firmwares_r_brand_i_a57a27_idx'), models.Index(fields=['-created_at'], name='firmwares_r_created_15c883_idx')],
                'unique_together': {('brand', 'model', 'variant_name', 'firmware_type')},
            },
        ),
        migrations.CreateModel(
            name='FirmwareStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('date', models.DateField(db_index=True, help_text='Stats for this date')),
                ('view_count', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('download_attempts', models.IntegerField(default=0)),
                ('successful_downloads', models.IntegerField(default=0)),
                ('failed_downloads', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Downloads / Views percentage')),
                ('success_rate', models.FloatField(default=0.0, help_text='Successful / Total attempts percentage')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'firmwares_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', '-view_count'], name='firmwares_s_date_ba4e58_idx'), models.Index(fields=['date', '-download_attempts'], name='firmwares_s_date_c69283_idx'), models.Index(fields=['content_type', 'object_id', 'date'], name='firmwares_s_content_ff7d44_idx')],
                'unique_together': {('content_type', 'object_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FirmwareView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('session_key', models.CharField(db_index=True, help_text='For anonymous tracking', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firmwares_view_log',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-viewed_at'], name='firmwares_v_content_e378c3_idx'), models.Index(fields=['-viewed_at'], name='firmwares_v_viewed__2dff8e_idx')],
            },
        ),
    ]
