# Generated by Django 5.2.12 on 2026-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0007_gsmarenadevice_chipset_gsmarenadevice_marketed_as_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='method_used',
            field=models.CharField(blank=True, default='', help_text='Scraping method that succeeded (spider, wayback, curl_cffi/*, httpx)', max_length=50),
        ),
    ]
