# Generated by Django 5.2.12 on 2026-03-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0008_syncrun_method_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='Set to True to signal the running scraper to stop gracefully.'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='running', max_length=10),
        ),
    ]
