# Generated by Django 5.2.12 on 2026-03-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0009_syncrun_cancel_requested_alter_syncrun_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='Brand logo URL (SVG preferred)', max_length=500),
        ),
    ]
