# Generated by Django 5.2.12 on 2026-03-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0010_add_brand_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief description about the brand and its firmware'),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show prominently on device catalog page'),
        ),
        migrations.AddField(
            model_name='brand',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text='Official brand website URL', max_length=500),
        ),
        migrations.AddField(
            model_name='model',
            name='also_known_as',
            field=models.TextField(blank=True, default='', help_text='Alternate names, comma-separated (e.g., POCO C81 Pro, Redmi A7 Pro)'),
        ),
        migrations.AddField(
            model_name='model',
            name='announced_date',
            field=models.DateField(blank=True, help_text='Announcement date', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='battery',
            field=models.CharField(blank=True, default='', help_text='Battery capacity (e.g., 5160 mAh)', max_length=64),
        ),
        migrations.AddField(
            model_name='model',
            name='chipset',
            field=models.CharField(blank=True, default='', help_text='Primary chipset (e.g., Mediatek Helio G100 Ultra (6nm))', max_length=256),
        ),
        migrations.AddField(
            model_name='model',
            name='codename',
            field=models.CharField(blank=True, default='', help_text='Internal codename (e.g., spinel, shiba, SM-S911B)', max_length=128),
        ),
        migrations.AddField(
            model_name='model',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text='Available colors (e.g., ["Black", "Forest Green", "Glacier Blue"])'),
        ),
        migrations.AddField(
            model_name='model',
            name='cpu',
            field=models.CharField(blank=True, default='', help_text='CPU description (e.g., Octa-core 2x2.2 GHz Cortex-A76)', max_length=256),
        ),
        migrations.AddField(
            model_name='model',
            name='dimensions',
            field=models.CharField(blank=True, default='', help_text='Dimensions (e.g., 164 x 75.7 x 7.8 mm)', max_length=128),
        ),
        migrations.AddField(
            model_name='model',
            name='display_size',
            field=models.CharField(blank=True, default='', help_text='Display size (e.g., 6.67")', max_length=64),
        ),
        migrations.AddField(
            model_name='model',
            name='gpu',
            field=models.CharField(blank=True, default='', help_text='GPU description (e.g., Mali-G57 MC2)', max_length=256),
        ),
        migrations.AddField(
            model_name='model',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Device photo URL', max_length=500),
        ),
        migrations.AddField(
            model_name='model',
            name='model_codes',
            field=models.JSONField(blank=True, default=list, help_text='All variant model codes (e.g., ["2510DRA23G", "2510DRA23E"])'),
        ),
        migrations.AddField(
            model_name='model',
            name='network_technology',
            field=models.CharField(blank=True, default='', help_text='Network type (e.g., GSM / HSPA / LTE / 5G)', max_length=128),
        ),
        migrations.AddField(
            model_name='model',
            name='os_version',
            field=models.CharField(blank=True, default='', help_text='Launch OS version (e.g., Android 15, HyperOS 2)', max_length=128),
        ),
        migrations.AddField(
            model_name='model',
            name='ram_options',
            field=models.JSONField(blank=True, default=list, help_text='RAM options in GB (e.g., ["4GB", "6GB", "8GB", "12GB"])'),
        ),
        migrations.AddField(
            model_name='model',
            name='regions',
            field=models.JSONField(blank=True, default=list, help_text='Regions with firmware availability (e.g., ["China", "Global", "EEA"])'),
        ),
        migrations.AddField(
            model_name='model',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('discontinued', 'Discontinued'), ('upcoming', 'Upcoming'), ('rumored', 'Rumored')], default='available', help_text='Market availability status', max_length=20),
        ),
        migrations.AddField(
            model_name='model',
            name='storage_options',
            field=models.JSONField(blank=True, default=list, help_text='Storage options (e.g., ["64GB", "128GB", "256GB", "512GB"])'),
        ),
        migrations.AddField(
            model_name='model',
            name='weight',
            field=models.CharField(blank=True, default='', help_text='Weight (e.g., 190 g)', max_length=64),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_code',
            field=models.CharField(blank=True, default='', help_text='Primary model code (e.g., SM-S911B)', max_length=64),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['codename'], name='model_codename_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['status'], name='model_status_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['chipset'], name='model_chipset_idx'),
        ),
    ]
