# Generated by Django 5.2.12 on 2026-03-26 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_ad_gate_config_post_ad_gate_enabled_and_more'),
        ('firmwares', '0011_brand_description_brand_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashingToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='wrench', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Flashing Tool Category',
                'verbose_name_plural': 'Flashing Tool Categories',
                'db_table': 'firmwares_flashingtoolcategory',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlashingTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tool_type', models.CharField(choices=[('oem', 'OEM Official'), ('crack', 'Crack / Patched'), ('local_market', 'Local Market'), ('free', 'Free / Freeware'), ('open_source', 'Open Source')], default='free', max_length=20)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('android', 'Android'), ('multi', 'Multi-Platform')], default='windows', max_length=20)),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('moderate', 'Moderate'), ('advanced', 'Advanced'), ('risky', 'Risky')], default='safe', max_length=20)),
                ('supported_chipsets', models.JSONField(blank=True, default=list, help_text='List of chipset names, e.g. ["MediaTek", "Qualcomm", "Spreadtrum"]')),
                ('download_url', models.URLField(blank=True, default='', max_length=500)),
                ('official_url', models.URLField(blank=True, default='', max_length=500)),
                ('version', models.CharField(blank=True, default='', max_length=50)),
                ('last_version_date', models.DateField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='flashing_tools/')),
                ('instructions', models.TextField(blank=True, default='', help_text='Usage instructions (Markdown supported)')),
                ('features', models.JSONField(blank=True, default=list, help_text='Feature bullet points')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='System requirements')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('supported_brands', models.ManyToManyField(blank=True, related_name='flashing_tools', to='firmwares.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='firmwares.flashingtoolcategory')),
            ],
            options={
                'verbose_name': 'Flashing Tool',
                'verbose_name_plural': 'Flashing Tools',
                'db_table': 'firmwares_flashingtool',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlashingGuideTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_template', models.CharField(help_text='Use {brand}, {model}, {chipset}, {guide_type} placeholders', max_length=300)),
                ('body_template', models.TextField(help_text='Markdown. Use {brand}, {model}, {chipset}, {tools}, {steps} placeholders')),
                ('summary_template', models.CharField(blank=True, default='', help_text='SEO summary template with same placeholders', max_length=500)),
                ('guide_type', models.CharField(choices=[('stock_flash', 'Stock Firmware Flash'), ('custom_rom', 'Custom ROM Installation'), ('unlock_bootloader', 'Bootloader Unlock'), ('root', 'Root Access'), ('recovery', 'Recovery Installation'), ('frp_bypass', 'FRP Bypass'), ('downgrade', 'Firmware Downgrade'), ('repair', 'Brick Repair'), ('general', 'General Guide')], default='stock_flash', max_length=30)),
                ('chipset_filter', models.CharField(blank=True, default='', help_text='Only generate for models with this chipset (partial match)', max_length=100)),
                ('auto_generate', models.BooleanField(default=False, help_text='Automatically generate blog posts for matching brand/models')),
                ('auto_publish', models.BooleanField(default=False, help_text='Auto-publish generated guides (vs. draft)')),
                ('is_active', models.BooleanField(default=True)),
                ('generated_count', models.PositiveIntegerField(default=0, help_text='Number of posts generated from this template')),
                ('brand', models.ForeignKey(blank=True, help_text='Generate guides for this brand. Leave empty for generic.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_templates', to='firmwares.brand')),
                ('recommended_tools', models.ManyToManyField(blank=True, related_name='guide_templates', to='firmwares.flashingtool')),
            ],
            options={
                'verbose_name': 'Flashing Guide Template',
                'verbose_name_plural': 'Flashing Guide Templates',
                'db_table': 'firmwares_flashingguidetemplate',
                'ordering': ['guide_type', 'brand__name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedFlashingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chipset', models.CharField(blank=True, default='', max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_guides', to='firmwares.brand')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_guides', to='firmwares.model')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashing_guide_source', to='blog.post')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_guides', to='firmwares.flashingguidetemplate')),
            ],
            options={
                'verbose_name': 'Generated Flashing Guide',
                'verbose_name_plural': 'Generated Flashing Guides',
                'db_table': 'firmwares_generatedflashingguide',
                'ordering': ['-created_at'],
                'unique_together': {('template', 'brand', 'model')},
            },
        ),
    ]
