# Generated by Django 5.2.12 on 2026-03-22 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Poll question', max_length=255)),
                ('mode', models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice')], default='single', max_length=10)),
                ('is_secret', models.BooleanField(default=False, help_text='Hide who voted')),
                ('close_at', models.DateTimeField(blank=True, help_text='Auto-close datetime', null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forum Poll',
                'verbose_name_plural': 'Forum Polls',
                'db_table': 'forum_forumpoll',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='#6366f1', help_text='Hex colour', max_length=7)),
                ('icon', models.CharField(blank=True, default='message-circle', help_text='Lucide icon name', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False, help_text='No new topics allowed')),
                ('is_visible', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False, help_text='Only invited users can see')),
                ('topic_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.forumcategory')),
            ],
            options={
                'verbose_name': 'Forum Category',
                'verbose_name_plural': 'Forum Categories',
                'db_table': 'forum_forumcategory',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ForumPollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='forum.forumpoll')),
            ],
            options={
                'verbose_name': 'Forum Poll Choice',
                'verbose_name_plural': 'Forum Poll Choices',
                'db_table': 'forum_forumpollchoice',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Markdown source')),
                ('content_html', models.TextField(blank=True, default='', help_text='Rendered & sanitized HTML')),
                ('action', models.IntegerField(choices=[(0, 'Comment'), (1, 'Moved'), (2, 'Closed'), (3, 'Unclosed'), (4, 'Pinned'), (5, 'Unpinned')], default=0)),
                ('is_removed', models.BooleanField(default=False)),
                ('is_modified', models.BooleanField(default=False)),
                ('modified_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Reply',
                'verbose_name_plural': 'Forum Replies',
                'db_table': 'forum_forumreply',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='forum/attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_attachments', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.forumreply')),
            ],
            options={
                'verbose_name': 'Forum Attachment',
                'verbose_name_plural': 'Forum Attachments',
                'db_table': 'forum_forumattachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReplyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Markdown content before edit')),
                ('content_html', models.TextField(help_text='Rendered HTML before edit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_reply_edits', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='forum.forumreply')),
            ],
            options={
                'verbose_name': 'Forum Reply History',
                'verbose_name_plural': 'Forum Reply Histories',
                'db_table': 'forum_forumreplyhistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('content', models.TextField(help_text='Markdown source')),
                ('content_html', models.TextField(blank=True, default='', help_text='Rendered & sanitized HTML')),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_globally_pinned', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now_add=True)),
                ('search_vector', models.TextField(blank=True, default='', help_text='Populated for PostgreSQL full-text search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.forumcategory')),
                ('last_reply_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_last_replies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Topic',
                'verbose_name_plural': 'Forum Topics',
                'db_table': 'forum_forumtopic',
                'ordering': ['-last_active'],
            },
        ),
        migrations.AddField(
            model_name='forumreply',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumtopic'),
        ),
        migrations.CreateModel(
            name='ForumPrivateTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_private_topics_created', to=settings.AUTH_USER_MODEL)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_info', to='forum.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum Private Topic',
                'verbose_name_plural': 'Forum Private Topics',
                'db_table': 'forum_forumprivatetopic',
            },
        ),
        migrations.AddField(
            model_name='forumpoll',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='forum.forumtopic'),
        ),
        migrations.CreateModel(
            name='ForumFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Offensive or abusive'), ('off_topic', 'Off-topic'), ('other', 'Other')], default='spam', max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_flags', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='forum.forumreply')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='forum.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum Flag',
                'verbose_name_plural': 'Forum Flags',
                'db_table': 'forum_forumflag',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_number', models.PositiveIntegerField(default=0, help_text='Last-read reply position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='forum.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum Bookmark',
                'verbose_name_plural': 'Forum Bookmarks',
                'db_table': 'forum_forumbookmark',
            },
        ),
        migrations.CreateModel(
            name='ForumTopicFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='forum.forumtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Favorite',
                'verbose_name_plural': 'Forum Favorites',
                'db_table': 'forum_forumtopicfavorite',
            },
        ),
        migrations.CreateModel(
            name='ForumTopicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('never', 'Never'), ('immediately', 'Immediately'), ('weekly', 'Weekly digest')], default='immediately', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='forum.forumtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Topic Subscription',
                'verbose_name_plural': 'Forum Topic Subscriptions',
                'db_table': 'forum_forumtopicsubscription',
            },
        ),
        migrations.CreateModel(
            name='ForumPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.forumpollchoice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.forumpoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Poll Vote',
                'verbose_name_plural': 'Forum Poll Votes',
                'db_table': 'forum_forumpollvote',
                'constraints': [models.UniqueConstraint(fields=('poll', 'choice', 'user'), name='forum_poll_vote_unique')],
            },
        ),
        migrations.CreateModel(
            name='ForumPrivateTopicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('private_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='forum.forumprivatetopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_private_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Private Topic Participant',
                'verbose_name_plural': 'Forum Private Topic Participants',
                'db_table': 'forum_forumprivatetopicuser',
                'unique_together': {('private_topic', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ForumMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The mentioned user', on_delete=django.db.models.deletion.CASCADE, related_name='forum_mentions_received', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='forum.forumreply')),
            ],
            options={
                'verbose_name': 'Forum Mention',
                'verbose_name_plural': 'Forum Mentions',
                'db_table': 'forum_forummention',
                'unique_together': {('reply', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ForumLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forum.forumreply')),
            ],
            options={
                'verbose_name': 'Forum Like',
                'verbose_name_plural': 'Forum Likes',
                'db_table': 'forum_forumlike',
                'unique_together': {('reply', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['category', '-last_active'], name='forum_topic_cat_active'),
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['user', '-created_at'], name='forum_topic_user_created'),
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['-is_globally_pinned', '-is_pinned', '-last_active'], name='forum_topic_pin_order'),
        ),
        migrations.AddIndex(
            model_name='forumreply',
            index=models.Index(fields=['topic', 'created_at'], name='forum_reply_topic_date'),
        ),
        migrations.AlterUniqueTogether(
            name='forumbookmark',
            unique_together={('topic', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='forumtopicfavorite',
            unique_together={('topic', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='forumtopicsubscription',
            unique_together={('topic', 'user')},
        ),
    ]
