# Generated by Django 5.2.12 on 2026-03-23 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emoji', models.CharField(help_text='Emoji character', max_length=10)),
                ('icon', models.CharField(blank=True, default='', help_text='Lucide icon name', max_length=64)),
                ('score', models.IntegerField(default=1, help_text='Reputation points awarded (+/- for negative)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_positive', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Forum Reaction',
                'verbose_name_plural': 'Forum Reactions',
                'db_table': 'forum_forumreaction',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ForumTrustLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'New User'), (1, 'Basic'), (2, 'Member'), (3, 'Regular'), (4, 'Leader')], unique=True)),
                ('title', models.CharField(help_text='Display title for this level', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Badge colour', max_length=7)),
                ('min_topics_created', models.PositiveIntegerField(default=0)),
                ('min_replies_posted', models.PositiveIntegerField(default=0)),
                ('min_likes_received', models.PositiveIntegerField(default=0)),
                ('min_likes_given', models.PositiveIntegerField(default=0)),
                ('min_days_visited', models.PositiveIntegerField(default=0)),
                ('min_topics_read', models.PositiveIntegerField(default=0)),
                ('can_flag', models.BooleanField(default=False)),
                ('can_create_polls', models.BooleanField(default=False)),
                ('can_upload_attachments', models.BooleanField(default=False)),
                ('can_send_private_messages', models.BooleanField(default=False)),
                ('can_edit_own_posts', models.BooleanField(default=True)),
                ('max_daily_topics', models.PositiveIntegerField(default=5)),
                ('max_daily_replies', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forum Trust Level',
                'verbose_name_plural': 'Forum Trust Levels',
                'db_table': 'forum_forumtrustlevel',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='forumreply',
            name='reaction_count',
            field=models.PositiveIntegerField(default=0, help_text='Total reactions (all types)'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='has_solution',
            field=models.BooleanField(default=False, help_text='Has an accepted best answer'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='rating_score',
            field=models.FloatField(default=0.0, help_text='Average star rating'),
        ),
        migrations.CreateModel(
            name='ForumBestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_solutions_marked', to=settings.AUTH_USER_MODEL)),
                ('reply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_best_answer', to='forum.forumreply')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='best_answer', to='forum.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum Best Answer',
                'verbose_name_plural': 'Forum Best Answers',
                'db_table': 'forum_forumbestanswer',
            },
        ),
        migrations.CreateModel(
            name='ForumOnlineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, default='', help_text='Current page description', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_online', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Online User',
                'verbose_name_plural': 'Forum Online Users',
                'db_table': 'forum_forumonlineuser',
            },
        ),
        migrations.CreateModel(
            name='ForumTopicMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_topic_title', models.CharField(max_length=255)),
                ('replies_moved', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_merges', to=settings.AUTH_USER_MODEL)),
                ('target_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_history', to='forum.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum Topic Merge',
                'verbose_name_plural': 'Forum Topic Merges',
                'db_table': 'forum_forumtopicmergelog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopicMoveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forum.forumcategory')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_moves', to=settings.AUTH_USER_MODEL)),
                ('to_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forum.forumcategory')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_history', to='forum.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum Topic Move',
                'verbose_name_plural': 'Forum Topic Moves',
                'db_table': 'forum_forumtopicmovelog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopicPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='allowed_prefixes', to='forum.forumcategory')),
            ],
            options={
                'verbose_name': 'Forum Topic Prefix',
                'verbose_name_plural': 'Forum Topic Prefixes',
                'db_table': 'forum_forumtopicprefix',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='forum.forumtopicprefix'),
        ),
        migrations.CreateModel(
            name='ForumUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_level', models.IntegerField(choices=[(0, 'New User'), (1, 'Basic'), (2, 'Member'), (3, 'Regular'), (4, 'Leader')], default=0)),
                ('custom_title', models.CharField(blank=True, default='', help_text='Custom rank title', max_length=100)),
                ('signature', models.TextField(blank=True, default='', help_text='Post signature (Markdown)')),
                ('signature_html', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('topic_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('likes_received', models.PositiveIntegerField(default=0)),
                ('likes_given', models.PositiveIntegerField(default=0)),
                ('solutions_count', models.PositiveIntegerField(default=0)),
                ('days_visited', models.PositiveIntegerField(default=0)),
                ('topics_read', models.PositiveIntegerField(default=0)),
                ('reputation', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True, default='')),
                ('ban_expires_at', models.DateTimeField(blank=True, null=True)),
                ('warning_level', models.PositiveIntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('last_posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum User Profile',
                'verbose_name_plural': 'Forum User Profiles',
                'db_table': 'forum_forumuserprofile',
            },
        ),
        migrations.CreateModel(
            name='ForumWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('final', 'Final Warning')], default='minor', max_length=10)),
                ('reason', models.TextField()),
                ('points', models.PositiveIntegerField(default=1, help_text='Warning points added')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-expire date', null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_warnings_issued', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='forum.forumreply')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='forum.forumtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Warning',
                'verbose_name_plural': 'Forum Warnings',
                'db_table': 'forum_forumwarning',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumCategorySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_topics', models.BooleanField(default=True)),
                ('notify_new_replies', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subscriptions', to='forum.forumcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_category_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Category Subscription',
                'verbose_name_plural': 'Forum Category Subscriptions',
                'db_table': 'forum_forumcategorysubscription',
                'unique_together': {('category', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ForumIPBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Permanent if null', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_ip_bans_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum IP Ban',
                'verbose_name_plural': 'Forum IP Bans',
                'db_table': 'forum_forumipban',
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='forum_ipban_ip')],
            },
        ),
        migrations.CreateModel(
            name='ForumReplyReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_reactions', to='forum.forumreaction')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.forumreply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Reply Reaction',
                'verbose_name_plural': 'Forum Reply Reactions',
                'db_table': 'forum_forumreplyreaction',
                'unique_together': {('reply', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ForumTopicRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='1 to 5 stars')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='forum.forumtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Topic Rating',
                'verbose_name_plural': 'Forum Topic Ratings',
                'db_table': 'forum_forumtopicrating',
                'unique_together': {('topic', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ForumTopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_tags', to='forum.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum Topic Tag',
                'verbose_name_plural': 'Forum Topic Tags',
                'db_table': 'forum_forumtopictag',
                'unique_together': {('topic', 'slug')},
            },
        ),
    ]
