# Generated by Django 5.2.12 on 2026-03-23 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0011_brand_description_brand_is_featured_and_more'),
        ('forum', '0002_forumreaction_forumtrustlevel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumattachment',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='4PDA-style download counter'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='linked_device',
            field=models.ForeignKey(blank=True, help_text='4PDA-style device link for this topic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_topics', to='firmwares.model'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='topic_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('firmware', 'Firmware'), ('faq', 'FAQ'), ('guide', 'Guide'), ('news', 'News'), ('review', 'Review'), ('bug_report', 'Bug Report')], default='discussion', help_text='4PDA-style topic classification', max_length=20),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='wiki_header',
            field=models.TextField(blank=True, default='', help_text='Wiki-style editable header (Markdown)'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='wiki_header_html',
            field=models.TextField(blank=True, default='', help_text='Rendered wiki header HTML'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='wiki_header_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='wiki_header_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_wiki_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ForumChangelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version string e.g. 1.2.3', max_length=50)),
                ('changes', models.TextField(help_text='Markdown description of changes')),
                ('changes_html', models.TextField(blank=True, default='')),
                ('released_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_changelog_entries', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entries', to='forum.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum Changelog',
                'verbose_name_plural': 'Forum Changelogs',
                'db_table': 'forum_forumchangelog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumFAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Short FAQ question label', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_entry', to='forum.forumreply')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_entries', to='forum.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum FAQ Entry',
                'verbose_name_plural': 'Forum FAQ Entries',
                'db_table': 'forum_forumfaqentry',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ForumWikiHeaderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Previous wiki header markdown')),
                ('content_html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_wiki_header_edits', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_header_history', to='forum.forumtopic')),
            ],
            options={
                'verbose_name': 'Forum Wiki Header History',
                'verbose_name_plural': 'Forum Wiki Header Histories',
                'db_table': 'forum_forumwikiheaderhistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumUsefulPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useful_marks', to='forum.forumreply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_useful_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Useful Post',
                'verbose_name_plural': 'Forum Useful Posts',
                'db_table': 'forum_forumusefulpost',
                'unique_together': {('reply', 'user')},
            },
        ),
    ]
