# Generated by Django 5.2.12 on 2026-03-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmwares', '0011_brand_description_brand_is_featured_and_more'),
        ('forum', '0003_forumattachment_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='brand_link',
            field=models.ForeignKey(blank=True, help_text="Link to firmware brand — category title should be brand marketing name only (e.g. 'Samsung', not 'Samsung Firmware')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_categories', to='firmwares.brand'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='model_link',
            field=models.ForeignKey(blank=True, help_text="Link to firmware model — category title should be model marketing name only (e.g. 'Galaxy S24 Ultra')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_model_categories', to='firmwares.model'),
        ),
    ]
